# Generated by Django 5.2.4 on 2025-09-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_board_creator_boardtask_created_at_boardtask_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='creator',
        ),
    ]
